/* (c) 2025 OpenGM groups */

#ifndef OPENGM_PQC_H
#define OPENGM_PQC_H

/* Generated with cbindgen:0.28.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

void mlkem768_keygen(uint8_t *ek, uint8_t *dk);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* OPENGM_PQC_H */
