/* (c) 2025 OpenGM groups */

#ifndef OPENGM_PQC_H
#define OPENGM_PQC_H

/* Generated with cbindgen:0.28.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * mlkem768_keygen_internal 密钥生成,dk必须指向(2 * k + k * k) * 512 + 96的缓冲区,k = 3
 * d,z必须指向32字节, d,z由调用者使用随机数发生器生成.
 */
void mlkem768_keygen_internal(uint8_t *dk, const uint8_t *d, const uint8_t *z);

int32_t mlkem768_encap_internal(uint8_t *key, uint8_t *c, const uint8_t *ek, const uint8_t *m);

int32_t mlkem768_decap(uint8_t *key, const uint8_t *c, const uint8_t *dk);

void mlkem768_encapkey_encode(uint8_t *ek_encoded, const uint8_t *ek_unencoded);

void mlkem768_decapkey_encode(uint8_t *dk_encoded, const uint8_t *dk_unencoded);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* OPENGM_PQC_H */
